name: tutorial
description: A new Flutter project.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  built_collection: 5.1.1
  built_value: 8.4.0
  cached_network_image: 3.2.1
  cloud_firestore: 4.2.0
  cloud_firestore_platform_interface: 5.9.1
  cloud_firestore_web: 3.1.1
  easy_debounce: 2.0.1
  file_picker: 4.5.1
  firebase_core: ^2.4.0
  firebase_core_platform_interface: 4.5.2
  firebase_core_web: 2.0.2
  flutter_animate: 1.0.0
  flutter_config: ^2.0.0
  flutter_cache_manager: 3.3.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  google_fonts: 3.0.1
  google_maps: 6.2.0
  google_maps_flutter: ^2.2.3
  google_maps_flutter_platform_interface: 2.2.1
  google_maps_flutter_web: 0.4.0+1
  image_picker: 0.8.5+3
  image_picker_android: 0.8.5+3
  image_picker_for_web: 2.1.10
  image_picker_ios: 0.8.6+1
  image_picker_platform_interface: 2.6.2
  intl: 0.17.0
  json_path: 0.4.1
  json_serializable: 6.3.1
  mime_type: 1.0.0
  page_transition: 2.0.4
  plugin_platform_interface: 2.1.3
  provider: 6.0.4
  shared_preferences: 2.0.15
  sqflite: 2.2.0+2
  timeago: 3.2.2
  url_launcher: 6.1.5
  firebase_auth: ^4.2.3
  sign_in_with_apple: ^4.3.0
  google_sign_in: ^5.4.4
  firebase_storage: ^11.0.8
  flutter_localizations:
    sdk: flutter
  address_search_field: ^5.0.3
  location: ^4.4.0
  get: ^4.6.5
  geocoding: ^2.1.0
  flutter_google_places: ^0.3.0
  geolocator: ^9.0.2
  custom_info_window: ^1.0.1
  location_geocoder: ^1.0.5

dev_dependencies:
  build_runner: 2.2.0
  built_value_generator: 8.4.0

  flutter_test:
    sdk: flutter

flutter_lints: ^1.0.0
get: ^4.1.4
http: any

geolocator: ^7.1.0
geocoding: ^2.0.0
google_maps_flutter: ^2.0.6 
flutter_typeahead: ^3.1.3
flutter_google_places: ^0.3.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
  